# Generated by Django 3.1.7 on 2021-06-08 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_stepcount', models.IntegerField(default='')),
                ('monday_activities', models.CharField(blank=True, max_length=32)),
                ('monday_date', models.DateField()),
                ('tuesday_stepcount', models.IntegerField(default='')),
                ('tuesday_activities', models.CharField(blank=True, max_length=32)),
                ('tuesday_date', models.DateField()),
                ('wednesday_stepcount', models.IntegerField(default='')),
                ('wednesday_activities', models.CharField(blank=True, max_length=32)),
                ('wednesday_date', models.DateField()),
                ('thursday_stepcount', models.IntegerField(default='')),
                ('thursday_activities', models.CharField(blank=True, max_length=32)),
                ('thursday_date', models.DateField()),
                ('friday_stepcount', models.IntegerField(default='')),
                ('friday_activities', models.CharField(blank=True, max_length=32)),
                ('friday_date', models.DateField()),
                ('saturday_stepcount', models.IntegerField(default='')),
                ('saturday_activities', models.CharField(blank=True, max_length=32)),
                ('saturday_date', models.DateField()),
                ('sunday_stepcount', models.IntegerField(default='')),
                ('sunday_activities', models.CharField(blank=True, max_length=32)),
                ('sunday_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
