# Generated by Django 3.1.7 on 2021-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='friday_stepcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='monday_stepcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='saturday_stepcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='sunday_stepcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='thursday_stepcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='tuesday_stepcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='wednesday_stepcount',
            field=models.IntegerField(),
        ),
    ]
