# Generated by Django 3.1.7 on 2021-06-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_auto_20210505_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='participant',
            new_name='user',
        ),
    ]
