# Generated by Django 3.1.7 on 2021-06-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_auto_20210608_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='published_date',
        ),
    ]
