# Generated by Django 3.1.7 on 2021-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_step_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='date',
            field=models.DateField(),
        ),
    ]
