# Generated by Django 3.1.7 on 2021-06-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_auto_20210608_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='date',
        ),
    ]
