# Generated by Django 3.1.7 on 2021-06-08 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_remove_step_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 21, 4, 8, 14238, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
